import { Action } from "@/types/action";

export const initialActions: Action[] = [
  {
    id: "act-1",
    task: "Follow up with Emily (Kenya) on revised flight quotes",
    client: "Emily Thornton",
    dueDate: "Today",
    priority: "High",
    owner: "Me",
    completed: true,
  },
  {
    id: "act-2",
    task: "Send updated proposal with private vehicle option to Catherine",
    client: "Catherine Family",
    dueDate: "Today",
    priority: "High",
    owner: "Me",
    completed: false,
  },
  {
    id: "act-3",
    task: "Confirm invoice & deposit instructions for Sondus",
    client: "Sondus Family",
    dueDate: "Tomorrow",
    priority: "Medium",
    owner: "Me",
    completed: false,
  },
  {
    id: "act-4",
    task: "Prepare weekly 1:1 pipeline notes & deal coaching topics",
    client: "Ashley Sales Hub",
    dueDate: "Tomorrow",
    priority: "Medium",
    owner: "Me",
    completed: false,
  },
  {
    id: "act-5",
    task: "Verify Bushwillow provisional hold release date and extensions",
    client: "Bushwillow Lodge",
    dueDate: "Overdue",
    priority: "High",
    owner: "Charianne",
    completed: false,
  },
  {
    id: "act-6",
    task: "Send Macatoo horse riding itinerary and packing checklist",
    client: "Justin Group",
    dueDate: "Overdue",
    priority: "Medium",
    owner: "Ashley",
    completed: false,
  },
  {
    id: "act-7",
    task: "Confirm domestic Cessna flight vouchers for Elena Rostova",
    client: "Elena Rostova",
    dueDate: "Thu 19 Sep",
    priority: "Low",
    owner: "Me",
    completed: false,
  },
  {
    id: "act-8",
    task: "Reply to luxury safari RFP for Serengeti group safari",
    client: "Dr. Alistair Ross",
    dueDate: "Fri 20 Sep",
    priority: "High",
    owner: "Ashley",
    completed: false,
  },
  {
    id: "act-9",
    task: "Update partner property rate sheet for 2027 safari season",
    client: "General Operations",
    dueDate: "Fri 20 Sep",
    priority: "Low",
    owner: "Charianne",
    completed: true,
  },
  {
    id: "act-10",
    task: "Log dietary restrictions and tent allocations for Vanderbilt charter",
    client: "Vanderbilt Group",
    dueDate: "Mon 23 Sep",
    priority: "Medium",
    owner: "Ashley",
    completed: false,
  },
  {
    id: "act-11",
    task: "Confirm Gorilla trekking permits provisional hold with RDB",
    client: "Marcus & Sarah Jenkins",
    dueDate: "Today",
    priority: "High",
    owner: "Me",
    completed: true,
  },
  {
    id: "act-12",
    task: "Review Holt Family private camp briefing packet",
    client: "Holt Family Safari",
    dueDate: "Yesterday",
    priority: "Low",
    owner: "Ashley",
    completed: true,
  },
];
