import { Opportunity } from "@/types/opportunity";

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-1",
    client: "Justin Family",
    destination: "Macatoo Horse Safaris & Victoria Falls",
    stage: "Discovery",
    value: "USD 9,800",
    numericValue: 9800,
    lastActivity: "Yesterday",
    nextAction: "Send equestrian questionnaire & camp combination quote",
    tripDate: "Mar 15 - Mar 25, 2027",
  },
  {
    id: "opp-2",
    client: "Dr. Alistair Ross",
    destination: "Serengeti Migration & Ngorongoro, Tanzania",
    stage: "Discovery",
    value: "USD 14,500",
    numericValue: 14500,
    lastActivity: "2 days ago",
    nextAction: "Clarify customized 4x4 open vehicle specifications",
    tripDate: "Jul 10 - Jul 22, 2027",
    attentionReason: "High-value opportunity",
  },
  {
    id: "opp-3",
    client: "Oliver & Penelope Sterling",
    destination: "Kidepo Valley & Bwindi Forest, Uganda",
    stage: "Discovery",
    value: "USD 15,300",
    numericValue: 15300,
    lastActivity: "5 days ago",
    nextAction: "Follow up on gorilla habituation permit dates",
    tripDate: "Aug 02 - Aug 15, 2027",
    attentionReason: "No recent activity",
  },
  {
    id: "opp-4",
    client: "Catherine Family",
    destination: "Kruger & Cape Town, South Africa",
    stage: "Proposal",
    value: "USD 12,400",
    numericValue: 12400,
    lastActivity: "3 days ago",
    nextAction: "Call group coordinator to review villa pricing",
    tripDate: "Dec 12 - Dec 28, 2027",
    attentionReason: "Proposal needs follow-up",
  },
  {
    id: "opp-5",
    client: "George & Hannah Miller",
    destination: "Mana Pools & Hwange, Zimbabwe",
    stage: "Proposal",
    value: "USD 13,800",
    numericValue: 13800,
    lastActivity: "1 day ago",
    nextAction: "Send revised walking safari itinerary and guide bio",
    tripDate: "Sep 08 - Sep 19, 2027",
  },
  {
    id: "opp-6",
    client: "Harrison & Associates",
    destination: "Madikwe & Tswalu Kalahari, South Africa",
    stage: "Proposal",
    value: "USD 26,000",
    numericValue: 26000,
    lastActivity: "4 days ago",
    nextAction: "Present corporate retreat itinerary & chef options",
    tripDate: "Feb 14 - Feb 24, 2027",
    attentionReason: "High-value opportunity",
  },
  {
    id: "opp-7",
    client: "Sondus Family",
    destination: "Okavango Delta & Chobe, Botswana",
    stage: "Invoice / Proposal",
    value: "USD 18,500",
    numericValue: 18500,
    lastActivity: "Today",
    nextAction: "Issue pro-forma invoice with helicopter transfer lines",
    tripDate: "Nov 02 - Nov 12, 2026",
    attentionReason: "High-value opportunity",
  },
  {
    id: "opp-8",
    client: "Vanderbilt Group",
    destination: "South Luangwa & Lower Zambezi, Zambia",
    stage: "Invoice / Proposal",
    value: "USD 34,000",
    numericValue: 34000,
    lastActivity: "6 days ago",
    nextAction: "Confirm charter deposit schedule with lead organizer",
    tripDate: "Jan 18 - Jan 29, 2027",
    attentionReason: "No recent activity",
  },
  {
    id: "opp-9",
    client: "Marcus & Sarah Jenkins",
    destination: "Volcanoes National Park, Rwanda",
    stage: "Invoice / Proposal",
    value: "USD 22,000",
    numericValue: 22000,
    lastActivity: "Yesterday",
    nextAction: "Collect deposit before permit hold expires on Thursday",
    tripDate: "Oct 05 - Oct 14, 2026",
    attentionReason: "Booking approaching deadline",
  },
  {
    id: "opp-10",
    client: "Elena Rostova",
    destination: "Sossusvlei Dunes & Skeleton Coast, Namibia",
    stage: "Booking",
    value: "USD 16,500",
    numericValue: 16500,
    lastActivity: "Yesterday",
    nextAction: "Send pre-departure briefing document & gear checklist",
    tripDate: "Sep 20 - Oct 01, 2026",
  },
  {
    id: "opp-11",
    client: "Holt Family Safari",
    destination: "Ruaha & Selous Reserve, Southern Tanzania",
    stage: "Booking",
    value: "USD 41,000",
    numericValue: 41000,
    lastActivity: "3 days ago",
    nextAction: "Finalize dietary preferences and charter tail numbers",
    tripDate: "Dec 01 - Dec 12, 2026",
  },
  {
    id: "opp-12",
    client: "The Sterling Family Trust",
    destination: "Linyanti & Savuti, Northern Botswana",
    stage: "Booking",
    value: "USD 29,500",
    numericValue: 29500,
    lastActivity: "4 days ago",
    nextAction: "Send anniversary celebration itinerary confirmation",
    tripDate: "Jun 18 - Jun 28, 2027",
  },
];
