import { ReportSummaryMetric, SalesSummaryRow } from "@/types/report";

export const reportSummaryMetrics: ReportSummaryMetric[] = [
  {
    id: "pipeline-val",
    label: "Current Pipeline Value",
    value: "USD 342,000",
    subtext: "Across 18 active opportunities",
    trend: "↑ 12% vs last week",
    isPositive: true,
  },
  {
    id: "active-opps",
    label: "Active Opportunities",
    value: "18",
    subtext: "Discovery (6), Proposal (5), Invoice (4), Booking (3)",
    trend: "↑ 4 new leads",
    isPositive: true,
  },
  {
    id: "bookings-month",
    label: "Bookings This Month",
    value: "5",
    subtext: "USD 96,000 in confirmed revenue",
    trend: "100% deposit rate",
    isPositive: true,
  },
  {
    id: "actions-completed",
    label: "Actions Completed",
    value: "8",
    subtext: "Tasks resolved across team",
    trend: "67% overall completion",
    isPositive: true,
  },
  {
    id: "actions-outstanding",
    label: "Actions Outstanding",
    value: "4",
    subtext: "2 due today, 2 due this week",
    trend: "1 high priority",
    isPositive: false,
  },
  {
    id: "bookings-watch",
    label: "Bookings to Watch",
    value: "4",
    subtext: "USD 47,900 combined watch value",
    trend: "2 closing this month",
    isPositive: true,
  },
];

export const salesSummaryRows: SalesSummaryRow[] = [
  {
    id: "row-1",
    category: "Botswana Luxury Safaris (Okavango & Chobe)",
    leadConsultant: "Ashley",
    activeDeals: 6,
    pipelineValue: "$124,500",
    confirmedBookings: 3,
    confirmedRevenue: "$48,000",
    conversionRate: "28.5%",
    avgBookingValue: "$16,000",
  },
  {
    id: "row-2",
    category: "South Africa & Cape Town Extensions",
    leadConsultant: "Kayleigh",
    activeDeals: 4,
    pipelineValue: "$68,000",
    confirmedBookings: 2,
    confirmedRevenue: "$24,800",
    conversionRate: "33.3%",
    avgBookingValue: "$12,400",
  },
  {
    id: "row-3",
    category: "Tanzania & Serengeti Expeditions",
    leadConsultant: "Ashley",
    activeDeals: 3,
    pipelineValue: "$65,500",
    confirmedBookings: 1,
    confirmedRevenue: "$41,000",
    conversionRate: "25.0%",
    avgBookingValue: "$41,000",
  },
  {
    id: "row-4",
    category: "Kenya Conservation & Riding Safaris",
    leadConsultant: "Kayleigh",
    activeDeals: 3,
    pipelineValue: "$28,000",
    confirmedBookings: 1,
    confirmedRevenue: "$7,200",
    conversionRate: "20.0%",
    avgBookingValue: "$7,200",
  },
  {
    id: "row-5",
    category: "Rwanda Gorilla Trekking & Primates",
    leadConsultant: "Kayleigh",
    activeDeals: 2,
    pipelineValue: "$56,000",
    confirmedBookings: 1,
    confirmedRevenue: "$22,000",
    conversionRate: "50.0%",
    avgBookingValue: "$22,000",
  },
];
